title: MIR-SMITH LTD
author: MIR-SMITH LTD
email: contact@example.com
description: >-
  Ruby Python Rails Flask Django Lektor Jekyll
  Docker PostgreSQL MongoDB Lua JavaScript
baseurl: ""
url: ""
github_username: mir-smith
rss: News Feed

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
github: [metadata] 

exclude:
   - Gemfile
   - Gemfile.lock
   - README.md

collections:
  pages:
    output: true

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
